### ISSUE TITLE
javafx GUI greeting on start and close on input 'bye'

### ISSUE THREAD

**Issue by banchiang** [nus-cs2103-AY2021S2/forum#107]
<img width="296" alt="gui" src="https://user-images.githubusercontent.com/72375578/106760085-61e89400-666e-11eb-895d-2865bbef3513.png">

Hello for my javafx code I have been following the tutorial https://se-education.org/guides/tutorials/javaFx.html. To produce the gui as shown above, I simply edited the method getResponse() in Duke . Currently the gui is unable to print the greeting message and close with the bye message. Any tips on implementing the two functionality cleanly? Thanks in advance!

**Comment by w2vgd** [comment]
Hint 1: For the greeting message, think about how similar it is to your current messages, i.e. what kind of node are you using to display the current messages now and also how are you adding them to your application now. After that, think about the sequence of event that happens when you boot up your application, i.e. the lifecyle of a JavaFX application (I have attached an image below for your reference). Think about when/where you can add that node to your current window :)

![image](https://user-images.githubusercontent.com/65358857/106762890-42069f80-6671-11eb-84ce-c9294117614e.png)

Hint 2: For the bye message, think about where you can add an additional check for the command passed in by the user. Can the check be done in `handleUserInput` or should it be done in `getResponse`? What method can you call to exit the program if the command is actually an exit/bye command?

Hope this helps 😄

**Comment by banchiang** [comment]
@w2vgd Thanks so much I think it works now! 
<img width="301" alt="guigreet" src="https://user-images.githubusercontent.com/72375578/106779176-b2b5b800-6681-11eb-96c1-9d62b61769ea.png">
<img width="299" alt="guigreetandbye" src="https://user-images.githubusercontent.com/72375578/106779276-cf51f000-6681-11eb-9811-68f5957acb93.png">
