### ISSUE TITLE
Probable Opposite Examples in SDLC Iterative Model

### ISSUE THREAD

**Issue by rajobasu** [nus-cs2103-AY2021S2/forum#11]
<img width="836" alt="Screenshot 2021-01-17 at 8 13 49 PM" src="https://user-images.githubusercontent.com/34958324/104840162-a4853f00-5900-11eb-9f7d-fd5b6bb8af61.png">

The examples are probably opposite, as in the example for the breadth-first should be in the depth-first, and vice versa, right?
Or is my understanding of these wrong, in which case would be glad if someone clarified!

**Comment by SoonKeatNeo** [comment]
Based on my understanding and based on the lecture materials last Friday, I believe they are accurate.

Breadth first approach implies “thin construction” of many of the different components that make up a software engineering project (e.g front end and back end developed in tandem, albeit they may not be fully complete), whereas depth first implies that a certain part of the project would be the priority and worked on first (e.g focus on the back end before the front end).

Better examples than this would be welcome I suppose :)

**Comment by damithc** [comment]
Good question. I think it depends on how you visualize the layout of the components.
Think of each component as peers rather than being on top of each other.

e.g., Suppose a software has three components A, B, C.
Visualize it as,
```
A --- B --- C
```
and not as,
```
A
B
C
```
So, in `A --- B --- C`, _breadth-first_ means doing some work in all three components while _depth-first_ means doing one component fully before moving into the next.

Does this visualization help you reconcile with the the text you quoted above?

**Comment by rajobasu** [comment]
Hi Prof, 
That is my understanding as well. But in that case, doesn't "building a new feature fully" mean completing a full component and thus is an example of depth-first ? (and similarly shouldn't "support for a feature to be added in a later iteration" more suitable for breadth-first rather than depth-first?

**Comment by damithc** [comment]
> That is my understanding as well. But in that case, doesn't "building a new feature fully" mean completing a full component and thus is an example of depth-first ? (and similarly shouldn't "support for a feature to be added in a later iteration" more suitable for breadth-first rather than depth-first?

Ah, I think the confusion is caused by equating _feature_ with _component_. They are orthogonal things. For example, UI is a component while 'add task' is a feature. So, implementing the 'add task' feature completely will require changes to all components including the UI but that doesn't mean the component UI needs to be complete (it's good enough if it can handle just the commands related to the 'add task' feature). Does that help with your doubt?

**Comment by rajobasu** [comment]
Oh okay I think I got it now. 
Thanks a lot prof :)
