### ISSUE TITLE
MainWindow.java issue

### ISSUE THREAD

**Issue by Yihe-Harry** [nus-cs2103-AY2021S2/forum#115]
Hi, I followed the tutorial about the MainWindow.java file, and I got this error.

![image](https://user-images.githubusercontent.com/67280376/107123564-230a4680-68d9-11eb-836c-84639c633a2a.png)

![image](https://user-images.githubusercontent.com/67280376/107123568-2dc4db80-68d9-11eb-96b3-48996ba5f555.png)

This there a quick fix to this?

**Comment by Yihe-Harry** [comment]
![image](https://user-images.githubusercontent.com/67280376/107123611-6c5a9600-68d9-11eb-87c5-7f37e9ffde36.png)

**Comment by tjtanjin** [comment]
If you are getting this error I assume you are on part 4 of the tutorial. In which case. there is a need to refactor the `getUserDialog` method to take in `String` in the parameter instead because the code in part 3 of the tutorial actually implemented `Label` as parameter.

Edit: A couple of other fields are affected as well such as `Image` and `ImageView`. A quick look at the codes from both part 3 and part 4 of the tutorial should reflect the parts that need refactoring :)
