### ISSUE TITLE
Blank lines result in checkstyle 'Trailing Whitespace' Error

### ISSUE THREAD

**Issue by zatkiller** [nus-cs2103-AY2021S2/forum#117]
I've blank lines in my code to improve the readability of the code and make it feel less cluttered. However, checkstyle is giving me the "Trailing Whitespace" error because of my blank lines. 

Is there any other way to remove the error without removing the blank lines?

**Comment by w2vgd** [comment]
Hi, I think that the "Trailing Whitespace" error is not caused by the blank lines, but rather it is caused by literally trailing white spaces in the specific line. 

For example, this does not give any checkstyle violations:
![image](https://user-images.githubusercontent.com/65358857/107137249-ab263580-6945-11eb-84d1-66a9a812cd67.png)

While this gives the "Trailing Whitespace" checkstyle violation:
![image](https://user-images.githubusercontent.com/65358857/107137257-cabd5e00-6945-11eb-81f2-9d3c1d2ea571.png)
(Notice the extra whitespace at the end of line 42?)

All you have to do is to go to the line as indicated by the checkstyle violation, and remove all the whitespaces that are at the end of the line. 
Or a faster method is actually to right click your java folder, and click `Reformat Code`.

Hope this helps 😄

**Comment by zatkiller** [comment]
I checked and there were no extra white spaces before the blank lines. I tried Reformat Code but it does not solve the errors either

**Comment by w2vgd** [comment]
> I checked and there were no extra white spaces before the blank lines. I tried Reformat Code but it does not solve the errors either

Would you like to share the error message from checkstyle as well as the corresponding line of code so that we can have a clearer picture of your problem?

**Comment by zatkiller** [comment]
There are many of the "trailing whitespace" checkstyle error messages. Here is one example with the corresponding line of code

Error message:
![Checkstyle error message](https://user-images.githubusercontent.com/59414467/107137590-e413d980-6948-11eb-8193-61cd4b66e528.png)

Line of code
![Code](https://user-images.githubusercontent.com/59414467/107137631-52f13280-6949-11eb-8442-1e8c52b9ce06.png)

**Comment by w2vgd** [comment]
Does your line 22 start from the beginning of the line as in this case:
![image](https://user-images.githubusercontent.com/65358857/107137673-d743b580-6949-11eb-96d8-117cdb8a08e8.png)

or it starts from the same indentation as the previous line as in this case:
![image](https://user-images.githubusercontent.com/65358857/107137680-dd399680-6949-11eb-9b00-a7c8ed83151d.png)

Edit(sorry typo earlier on): The first case is the correct version and the second case will give the error.

**Comment by zatkiller** [comment]
Oh mine is the 2nd case. How do I fix it? I tried backspacing but the blank line gets removed

**Comment by zatkiller** [comment]
Managed to fix it on my own. Thanks a lot for the help @w2vgd !!

**Comment by damithc** [comment]
This might help https://se-education.org/guides/tutorials/intellijCodeStyle.html#tweak-auto-remove-trailing-spaces
