### ISSUE TITLE
GitHub Actions CI with Gradle fails to build

### ISSUE THREAD

**Issue by ampan98** [nus-cs2103-AY2021S2/forum#121]
I copied the provided gradle.yml file into the workflows folder, as shown in this commit.
https://github.com/ampan98/ip/commit/2d6015993b269cc71a09c2bf38f494cfcd13b57d

However, it fails to build on GitHub Actions. 
![image](https://user-images.githubusercontent.com/65174167/107382809-44fb0780-6b2b-11eb-8ef7-4d5685c1f770.png)

I understand that this is a permission issue but I'm not sure how to change permissions on GitHub (or if I even need to)?

**Comment by JQChong** [comment]
Hi, I have encountered similar issues before, and I resolved it by adding the following lines:

`-name: Make gradlew executable`

` run: chmod +x ./gradlew`

in my gradle.yml. Maybe you want to try it out?

Edit: to clarify, you will need to place it before the lines
`- name: Build and check with Gradle`

` run: ./gradlew check`
so that the changes to the permission will take effect before gradlew runs

**Comment by lirc572** [comment]
You can also try the following to give gradlew executable permission with git:

```
git update-index --chmod=+x gradlew
```

Reference: <https://stackoverflow.com/questions/21691202/how-to-create-file-execute-mode-permissions-in-git-on-windows>

**Comment by ampan98** [comment]
@JQChong I tried your solution but it didn't work.
@lirc572 this solution worked for me. Thanks for the reference also.

**Comment by lirc572** [comment]
Glad it worked!

> @JQChong I tried your solution but it didn't work.

Just for your information, to make @JQChong 's solution work, you'll need to run `chmod +x ./gradlew` before calling `gradlew` in your `gradle.yml` :blush:

**Comment by ampan98** [comment]
Oh right that makes sense. :|
