### ISSUE TITLE
How to best deal with missing return statement error for non-void methods without having to return null?

### ISSUE THREAD

**Issue by CSmortal** [nus-cs2103-AY2021S2/forum#154]
So after learning more on code quality/standards, I was convinced that the default case for switch statements and else clause for if else blocks should almost always be exclusively for throwing exceptions or `assert false`/ `throw new AssertionError()` statements. But this doesn't get around the issue of having to return something from a non-void method. Returning null has always been my go-to until now for convenience sake, so I'm not sure what to do now.

**Comment by kouyk** [comment]
My take is that If an exception is thrown then the lack of a return statement should not matter. So I guess your problem at hand is with assertions. Since assertions are not meant to be recoverable and indicates a bug to be fixed, it should not be triggered at all if the code is correctly written. If it is expected to occur then an exception should have been thrown in order to be caught. Using `assert false` in default case or else blocks is equivalent to not using it since assertions can be disabled. So ideally your code should have a happy path that always returns something valid, assertions are there to help you catch unexpected bugs when assertions are enabled.

**Comment by w2vgd** [comment]
Perhaps you can provide us with some examples on what are the cases that will meet such issues? In my opinion, its far too definite to say that the default case and else clause should be used solely for throwing exceptions/errors.

**Comment by candyhy** [comment]
agree with @w2vgd that it is too hasty to conclude default cases and else clause should be used solely for throwing exceptions/errors. Printing in the default case can help debugging(to affirm that the switch clause is reached) since there can be new cases as we add new features to a software.
Personally, I have used switch clauses in non-void methods, and I find no issue in the return statements as the default clause is never reached. Maybe you can consider handling all cases in the switch clause so the default case will never be reached? Variables can be declared as `Integer count;` instead of `Integer count = null;`
Hope this helps! maybe you can consider showing us your code for more concrete help:)

**Comment by chewterence** [comment]
@CSmortal could you clarify with an example?
did you mean something like:

```java
public Fruit parseCommand(String command) throws CommandNotFoundException {
    switch (command) {
    case "apple":
        return new Apple();
    case "banana":
        return new Banana();
    default:
        throw new CommandNotFoundException();
    }
}
```

versus


```java
public Fruit parseCommand(String command) {
    switch (command) {
    case "apple":
        return new Apple();
    case "banana":
        return new Banana();
    default:
        return null;
        // return a null here instead of throwing an exception
    }
}
```
---

Also, I found [this](https://softwareengineering.stackexchange.com/questions/402599/throw-an-exception-in-default-case-of-a-switch) somewhat relevant, and perhaps linked to the use of enums.

**Comment by CSmortal** [comment]
@chewterence 
for your 1st method that `throws CommandNotFoundException`, what if i didnt want the method to throw any exception, like if i wanted to handle any exceptions in this method, i.e.
```
public Fruit parseCommand(String command) {
    try {
        switch (command) {
        case "apple":
            return new Apple();
        case "banana":
            return new Banana();
        default:
            throw new CommandNotFoundException();
        }
    } catch (Exception ex) {
        // Do something
    }
}  
```

I think this will have compile errors since the "missing return statement" error appears. I'm more certain this appears for if/else blocks instead of switch statement.


As an example of the issue in my code, the situation looks something like this:
```
public Fruit parseCommand(String command) {
    try {
        if (command == "apple") {
            return new Apple();
        } else if (command == "banana") {
            throw new Exception("what is a banana?");
        } else {
            assert false : "You shouldn't reach this block";
        }
    } catch (Exception ex) {
        // Do something
    }
    
    return null;
}
```

In the code above, I'm assuming the command can only be `"apple"` or `"banana"`, so I'm trying to test that assumption with this code here. One else if block doesn't have a return statement, but even if it does, i still get the issue of "missing return statement" if i dont include the `return null` after the try catch block. And for the reason why i put the `assert false` statement in the else block, following [this assertions tutorial in Wk5 topics,](https://docs.oracle.com/javase/8/docs/technotes/guides/language/assert.html) in the Suits example with the part on "Internal Invariants", it says we should test the assumption that the suit variable is one of the four types, so thus we should put a `assert false` statement in the default case of switch statement (and by extension the else block for if else blocks). So, regarding what @kouyk said about assertions "should not be triggered at all if the code is correctly written", I don't think his way should be the approach to writing assertions. Following the link, we should be testing assumptions, not riding on them.

**Comment by kouyk** [comment]
For the oracle tutorial, they are using enums, which should only take on a limited number of values in which all of them should have a switch case, the only time that the assertion occurs is when a new enum value is added but not handled. This is a good scenario to use assertions since it indicates that the code needs to be updated. Furthermore, the switch case does not return, so presumably there will be a happy path below to handle the returning. For your example, you might want to explain the rationale behind asserting and catching that very same assertion when it can be handled all within the same else block. I would assume if the `command` is invalid, a parsing exception should either be raised like for the banana scenario since it is not to be handled by the `parseCommand` method, or there is a default `Fruit` to be returned instead.

**Comment by CSmortal** [comment]
> 
> 
> agree with @w2vgd that it is too hasty to conclude default cases and else clause should be used solely for throwing exceptions/errors. Printing in the default case can help debugging(to affirm that the switch clause is reached) since there can be new cases as we add new features to a software.
> Personally, I have used switch clauses in non-void methods, and I find no issue in the return statements as the default clause is never reached. Maybe you can consider handling all cases in the switch clause so the default case will never be reached? Variables can be declared as `Integer count;` instead of `Integer count = null;`
> Hope this helps! maybe you can consider showing us your code for more concrete help:)

@candyhy I'm not very familiar with throwing and switch statements, but if you're enumerating all your cases ( not using the default case as your last case to handle the last possible input to the switch statement ), unless your method that contains the switch statement explicitly throws something in its method declaration, your default case should cause the "missing return statement" if it does not have a return statement. Please correct me if I'm wrong

**Comment by CSmortal** [comment]
> 
> 
> For the oracle tutorial, they are using enums, which should only take on a limited number of values in which all of them should have a switch case, the only time that the assertion occurs is when a new enum value is added but not handled. This is a good scenario to use assertions since it indicates that the code needs to be updated. Furthermore, the switch case does not return, so presumably there will be a happy path below to handle the returning. For your example, you might want to explain the rationale behind asserting and catching that very same assertion when it can be handled all within the same else block. I would assume if the `command` is invalid, a parsing exception should either be raised like for the banana scenario since it is not to be handled by the `parseCommand` method, or there is a default `Fruit` to be returned instead.

@kouyk Ok so assuming its not enums, and each case in the switch statement returns something, then the solution to escape the "missing return statement" should be a happy path, or a default "Fruit" returned in the case of the parseCommand() method? Because the relevant code in my iP doesn't have a happy path (its checking what the input is "==" to, not checking against some boolean condition or smth), and i dont want to return a default object.

**Comment by kouyk** [comment]
I took a brief look at your iP code, I assume that the relevant part of your code in in `Parser.java`, namely the `Parser::parseRemainder` right? Do correct me if I am wrong. My understanding of exceptions is that it is thrown when something out of the norm has occurred, and it is something that the current method that is throwing the exception should not be able to handle. Hence throwing an exception will skip the rest of the execution and raise it through the call stack for it to be caught. If the current method can handle the issue, then an exception should not be thrown, it can be handled directly at the place where the exception is thrown. 

I understood your point of not returning a default object since there's none for this case, so throwing an exception to be caught by the call stack makes a lot of sense, since an exception during parsing indicates no valid return value, and hence the method calling `Parser::parseRemainder` ideally should catch this exception and be able to handle it, i.e. printing the error message.

(Exception throwing is quite literal, it's about throwing the problem to someone else, so I don't have to handle it)

**Comment by damithc** [comment]
> I understood your point of not returning a default object since there's none for this case, so throwing an exception to be caught by the call stack makes a lot of sense, since an exception during parsing indicates no valid return value, and hence the method calling `Parser::parseRemainder` ideally should catch this exception and be able to handle it, i.e. printing the error message.

Correct. If the method promises to return something, 'handling the exception inside the method' doesn't give you an excuse to break that contract. That means, 'handling' should result in a legit return object nevertheless. If you are unable come up with a return object during that handling, that means you are handling the exception in the wrong place. The exception should be handed by the caller instead.

**Comment by candyhy** [comment]
> > agree with @w2vgd that it is too hasty to conclude default cases and else clause should be used solely for throwing exceptions/errors. Printing in the default case can help debugging(to affirm that the switch clause is reached) since there can be new cases as we add new features to a software.
> > Personally, I have used switch clauses in non-void methods, and I find no issue in the return statements as the default clause is never reached. Maybe you can consider handling all cases in the switch clause so the default case will never be reached? Variables can be declared as `Integer count;` instead of `Integer count = null;`
> > Hope this helps! maybe you can consider showing us your code for more concrete help:)
> 
> @candyhy I'm not very familiar with throwing and switch statements, but if you're enumerating all your cases ( not using the default case as your last case to handle the last possible input to the switch statement ), unless your method that contains the switch statement explicitly throws something in its method declaration, your default case should cause the "missing return statement" if it does not have a return statement. Please correct me if I'm wrong

@CSmortal 
If your cases handles all possible enums, and the default case will never be reached, then throwing an assertion error in the default case does not require an exception to be added to the method signature. In my opinion, throwing an assertion error in a default clause that shouldn't be reached makes sense. 

Attached below is an example of use of assertion error in default clause:
![WhatsApp Image 2021-02-18 at 12 11 13 PM](https://user-images.githubusercontent.com/70088064/108304738-9bc7a780-71e3-11eb-9daa-943bcbed733c.jpeg)

However, this scenario only applies when you can list out all possible case values, because assertions are meant to detect flaws in the programmer's code and not because of an invalid user input (this should be handled by exceptions). So as what Prof @damithc and @kouyk has mentioned, you may want to handle the exception in the calling parent method or just handle the issue directly at the place where the issue occurred.

**Comment by w2vgd** [comment]
> ```
> public Fruit parseCommand(String command) {
>     try {
>         if (command == "apple") {
>             return new Apple();
>         } else if (command == "banana") {
>             throw new Exception("what is a banana?");
>         } else {
>             assert false : "You shouldn't reach this block";
>         }
>     } catch (Exception ex) {
>         // Do something
>     }
>     
>     return null;
> }
> ```

Do note that you should not use use `AssertionError` or `assert` statements to handle invalid user input. Imagine if the user accidentally pass in a command "appl" and then the program crashes because of a small typo, I think that the user will be quite shocked to say the least. The program cannot recover from an assertion error because throwing an assertion error will mean that something has gone horribly wrong in the code at this point and any further execution may likely result in unwanted consequences. 

As what @candyhy has mentioned, you should use exceptions to handle invalid user input and propagate that exception to be handled by the caller parent method instead. There is also nothing wrong with adding that the method throws some exceptions in the method signature too. This is to help you ensure that any method who calls this method will have to handle this exception.

**Comment by CSmortal** [comment]
> 
> 
> I took a brief look at your iP code, I assume that the relevant part of your code in in `Parser.java`, namely the `Parser::parseRemainder` right? Do correct me if I am wrong. 
> 

@kouyk yup, thats the code I'm having the issue with. So after reading Prof @damithc 's comment, for `Parser::parseRemainder()`, should I be including a `throws Exception` in its method signature, then remove the try catch block in the method, then I will no longer have the "missing return statement" error if i exclude the `return null`?

**Comment by kouyk** [comment]
Yup you're right, since your if-else block is the only block left, and every block returns a valid object if no exceptions raised, it should not complain anymore.

**Comment by vevek** [comment]
> > I took a brief look at your iP code, I assume that the relevant part of your code in in `Parser.java`, namely the `Parser::parseRemainder` right? Do correct me if I am wrong.
> 
> @kouyk yup, thats the code I'm having the issue with. So after reading Prof @damithc 's comment, for `Parser::parseRemainder()`, should I be including a `throws Exception` in its method signature, then remove the try catch block in the method, then I will no longer have the "missing return statement" error if i exclude the `return null`?

Sounds correct. Also as @w2vgd has said, instead of asserting that the user has input a wrong command. It would be better to throw an exception and handle it. I would have done something similar to this:

````
public Fruit parseCommand(String command) throws Exception {
    Fruit fruit;

    if (command == "apple") {
       fruit = new Apple();
    } if (command == "pear") {
       fruit = new Pear();
    } else if (command == "banana") {
        throw new Exception("what is a banana?");
    } else {
        // Should not be asserting here as this is a user error. Should throw an exception instead.
        throw new Exception("Invalid command etc");
    }

    return fruit;
}
````

**Comment by CSmortal** [comment]
thanks all, can I also ask when should I use assert statements over throwing AssertionError()? The oracle docs shows AssertionError would be better for those Internal Invariants situations and for the same issue of "missing return statement" error inside a non void method. Coupled with java disabling assertions by default, I can't see when to use simple assert statements.

**Comment by vevek** [comment]
> thanks all, can I also ask when should I use assert statements over throwing AssertionError()? The oracle docs shows AssertionError would be better for those Internal Invariants situations and for the same issue of "missing return statement" error inside a non void method. Coupled with java disabling assertions by default, I can't see when to use simple assert statements.

I found [this link](http://onebigfunction.com/blog/2015/11/16/assert-vs-assertionerror/) to be useful!
