### ISSUE TITLE
Refactoring data or not?

### ISSUE THREAD

**Issue by Cheng20010201** [nus-cs2103-AY2021S2/forum#156]
Hi, was trying to do the tutorial (removing a field) for tp code base, just observed sth:

when I do the refactoring (removing the `phone` field of `Person`), the tutorial mentions it is better to [refactor the test data as well so that the old version does not accumulate](https://nus-cs2103-ay2021s2.github.io/tp/tutorials/RemovingFields.html#tidying-up).

That part I have no problem with. But then I wonder whether we also need to refactor the json data under `[root]/data/`. According the `.gitignore`, that data file is not version controlled, which means if I delete the `phone` fields in the data file, then I switch to other branches, I would have issues loading data because some compulsory data field is missing.

Then, does it mean I should not edit that data file when refactoring? I understand **in this case** if I do not edit the data file the code would work for my working branches and other branches, but are there any possible implications (which will make refactoring the un-version-controlled data file necessary)?

If there are no such implications, it is clear that I should not refactor the un-version-controlled data file whenever I refactor my code. But I cannot get my logic correct here (either prove or give counter examples). Help needed. :)

**Comment by SoonKeatNeo** [comment]
The data in the `data/addressbook.json` is populated by the [sample data utility](https://github.com/nus-cs2103-AY2021S2/tp/blob/master/src/main/java/seedu/address/model/util/SampleDataUtil.java) if it is not present, so I think if your working data is messed up later you could let it re-populate again later.

Personally, I did not remove the address field in the data file while doing the removing field tutorial since it's not in git and by nature it's fine for JSON files to have extra fields anyway (although maybe in an ideal scenario the software developer would code to remove unused fields in future revisions to patch if they are no longer necessary).

**Comment by Cheng20010201** [comment]
> The data in the `data/addressbook.json` is populated by the [sample data utility](https://github.com/nus-cs2103-AY2021S2/tp/blob/master/src/main/java/seedu/address/model/util/SampleDataUtil.java) if it is not present, so I think if your working data is messed up later you could let it re-populate again later.

This one I didn't notice. Thanks.
