### ISSUE TITLE
UnsupportedClassVersionError for jar. 

### ISSUE THREAD

**Issue by colintkn** [nus-cs2103-AY2021S2/forum#170]
I received this error. 

> An automated smoke testing of your iP JAR file found the application crashes with the following error(s) upon launching:
On Windows, using Java 11, for the Percy.jar uploaded on 02-12-2021 (MM-DD-YYYY) at 13:57:31:
Error: LinkageError occurred while loading main class Launcher java.lang.UnsupportedClassVersionError: Launcher has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0

I received this for both Linux and Mac versions. 

I think this problem comes from compiling the program using java 14 instead of java 11.

I set the default java version on my computer to java 11.0.9 and ran the build again with reference to #158. 

Is there a way to check the runtime of your jar file to make sure it adheres to the right versions.

**Comment by damithc** [comment]
> I received this for both Linux and Mac versions.

@colintkn The same error was reported for Windows as well right? Because this error is not specific to the OS. 

You should be able to reproduce it by running the JAR file using Java 11 even in your own computer. Once you can reproduce it in your own computer, you should be able to verify yourself after the JAR has been build correctly.

**Comment by colintkn** [comment]
Ok thank you.
