### ISSUE TITLE
Interfaces: when and why?

### ISSUE THREAD

**Issue by tlylt** [nus-cs2103-AY2021S2/forum#176]
Hi guys, recently I had quite a few discussions with others on interfaces and why do we need them. 

Browsing through our textbook doesn't seem to provide me with adequate reasons why interfaces are needed. I acknowledge that interfaces do the job of specifying certain common behaviours that classes can share and allow for (multiple) inheritances and expressing is-a relationship in OOP fashion. However, it seems that besides multiple inheritances, abstract classes can do the job of interfaces just as perfectly. Also while researching for an answer, I found a casual comment by Robert C. Martin (Uncle Bob) in one of his videos that interfaces are a lousy way of solving multiple inheritance issues in Java.

If I may quote some discussions that came up in my TP team chat:
"only good for implementations like list, collection etc" @ong6
"interface ... enforces methods on whoever implements them so it's like a safeguard?" @tjtanjin 
and myself:
"I think the use of interfaces is more when you have client-facing code, example a manufacturer will probably provide interfaces that tell software companies that want to make compatible software for this hardware that it needs to implement the certain interface in order to make the parts move etc"

At the end of it, I am not convinced and also not sure if the above discussions do justice to what interfaces are really for.  Other possible reasons that I know of are that interfaces seem to be important for inverting dependencies and also the principle of programming to an interface.

So my questions are:
Can someone provide a succinct example to illustrate why do we need to use interfaces? And if we do, why not go with abstract classes??

**Comment by YuFeng0930** [comment]
I agree the quote from you, and I think that is the main reason to use interfaces. As for "why not use abstract class?", I think the need for abstract class (on top of interface) is just for us to define some functions that are the same in its child class, so as to reduce repetition. Other than that, a class can implement multiple interfaces, which gives us more flexibility, while a class cannot extend multiple abstract classes.

**Comment by damithc** [comment]
While discussing this topic, keep in mind that these two things are not the same:
1. The general concept of an _interface_, as in _separate the interface from the implementation_.
2. The Java construct called `interface`. 

The latter is only _one_ way to implement the former in Java. Some languages (e.g., C++) don't even have a construct called `interface` in which case an abstract class can be used to achieve the same. Likewise, you can use an `abstract class` to act like an _interface_ in Java too.

But as @YuFeng0930 mentioned, there are some situations where you have to use an `interface` and not an `abstract class` due to the way Java works. So, it's a matter of looking at features/limitations of each and choosing the one that fits. But don't let that choice worry you too much; you can always replace one with the other if things didn't work out as you expected :-)

**Comment by tlylt** [comment]
> While discussing this topic, keep in mind that these two things are not the same:
> 
> 1. The general concept of an _interface_, as in _separate the interface from the implementation_.
> 2. The Java construct called `interface`.
> 
> The latter is only _one_ way to implement the former in Java. Some languages (e.g., C++) don't even have a construct called `interface` in which case an abstract class can be used to achieve the same. Likewise, you can use an `abstract class` to act like an _interface_ in Java too.
> 
> But as @YuFeng0930 mentioned, there are some situations where you have to use an `interface` and not an `abstract class` due to the way Java works. So, it's a matter of looking at features/limitations of each and choosing the one that fits. But don't let that choice worry you too much; you can always replace one with the other if things didn't work out as you expected :-)

Thank you. The main reason why I was confused is indeed speaking about interfaces both as a Java language construct and as an abstraction concept. Will close this issue for now until I have more questions on this topic :smile:
