### ISSUE TITLE
Updating developer guide

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#177]
Hi, for the user stories and use cases segments under the developer guide, are we supposed to include as many as we can, or are we supposed to include only those that are essential? I think that it is likely to be just including the important ones because the former will likely cause the DG to be overly long. However there are different priority levels assigned to each user story, which make it seem like we should add all of them. 

Hope to seek clarification here. Thank you.

**Comment by tlylt** [comment]
As mentioned in the module website:
> User stories: This can include user stories considered but will not be included in the final product.
Use cases: Give use cases (textual form) for a few representative user stories that need multiple steps to complete.

I believe having some representative ones will do for now, as they can evolve and be added later on in the process of development. Requirements change all the time... :smile: (Correct me if I am wrong)

**Comment by damithc** [comment]
Include **at least the essential ones** (because missing essential user stories or use cases is considered a bug). In addition, try to include the ones that you think you'll be doing by v1.4. You can add more along the way too e.g., if you implement a user story that you didn't plan for in the beginning.

**Comment by w2vgd** [comment]
Okay! Thanks for the clarification.
