### ISSUE TITLE
Markdown files line length

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#186]
Hi, just curious if there are any restrictions on the line length in markdown files? 

I know that line breaks do not matter in `.md` files as line breaks only translate to a space, but what are the benefits of having such long lines over breaking these long lines into say, 120 characters per line? (since the given files in Addressbook are using a single line for almost every paragraph, with some lines going up to almost 1000 characters!)

**Comment by damithc** [comment]
One downside of breaking a paragraph into multiple lines of fixed length is that a single change in future might require you to adjust multiple lines below it e.g., if the change causes the line to exceed the max line length, you'll have to move some of it the the next line, which can make that line spill over to the next line, and so on. Hence, not splitting paragraphs into fixed-length lines reduces the potential 'blast radius' of future changes.

**Comment by vevek** [comment]
Testing it out on my projects md files, I found that like you said it did not matter whether a long line was used instead of one that is kept consistently below 120 characters.  

The only benefit I can think of is being able to copy & paste into the md file without spending too much time creating line breaks just to ensure that lines are kept below 120 characters. I would still prefer to keep each line below 120 characters as it is easier to edit and maintain.

**Comment by w2vgd** [comment]
@vevek This was what I thought initially too, as reading the lines and editing will be much easier with shorter lines. But I guess Prof @damithc raised a very good point about the maintenance of the files in the future.

**Comment by damithc** [comment]
BTW, IDEs have a feature called 'soft wrap' that will automatically move the content to the next line if the line is longer than the width of the window. It's 'soft' because the wrapping is only done in the UI; the file remains unchanged. Once you enable soft wrapping, longer lines will be as easy to read/edit as short ones.

![image](https://user-images.githubusercontent.com/1673303/109327505-5ebe7d80-7893-11eb-931f-941312f7e30e.png)

**Comment by w2vgd** [comment]
Thanks prof @damithc for the tip! This will be very useful for editing the documentation files 😃 

For those who wants to enable soft wraps in Intellij, can go to `Settings` -> `Editor` -> `General`, and under the Soft Wraps section, check this box:
![image](https://user-images.githubusercontent.com/65358857/109329084-21f38600-7895-11eb-87ab-84ebf50e5e9a.png)

**Comment by damithc** [comment]
Thanks @w2vgd for sharing how to enable soft wrapping in Intellij. You can consider posting it as a separate issue, for better visibility.

**Comment by w2vgd** [comment]
@damithc Sure!
