### ISSUE TITLE
Git commit message format

### ISSUE THREAD

**Issue by tjtanjin** [nus-cs2103-AY2021S2/forum#19]
Hello!

For git commit messages, I have noticed an inconsistency between an [example given](https://nus-cs2103-ay2021s2.github.io/website/schedule/week2/topics.html#W2-3) in the week 2 topics and the [SE education guide](https://se-education.org/guides/conventions/git.html), the latter which I just learned about. For clarity sake, the styles shown in the above 2 links are as below.

*Example in week 2 topics:*
<img width="802" alt="Screenshot 2021-01-19 at 11 18 11 AM" src="https://user-images.githubusercontent.com/43908963/104983621-12884e00-5a48-11eb-857c-2a855d2031fb.png">

*Guidelines in SE education guide:*
<img width="389" alt="Screenshot 2021-01-19 at 11 18 19 AM" src="https://user-images.githubusercontent.com/43908963/104983633-17e59880-5a48-11eb-8cd1-a41e251c6017.png">

My past commits have all been done following the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), which is more inline with the first example above (the notable difference is the capitalisation of the first word in the commit message). Moving forward, may I know which modes of commit styles are allowed and should the case be that the first word must be capitalised, does that mean I have to update all past commit messages? ;-;

Thank you!

**Comment by damithc** [comment]
@tjtanjin Go with the se-edu guide. I'll update the textbook to eliminate the inconsistency. Thanks for pointing out the inconsistency.

Having said that, the two are different things; one teaches the technique and the other specify a convention. The former remains the same for every project while the latter can vary from project to project.

**Comment by tjtanjin** [comment]
Hello Prof @damithc!

Thank you for the response. I am slightly confused by your second statement. The technique taught in the SE-edu guide seems to enforce capitalisation of the first word in the commit message whereas the convention does not. Wouldn't this mean they do not sit well with each other? In fact, the education guide and convention are both contradicting each other so if the former is always the same for every project, wouldn't it mean the latter is never followed? Sorry for the many questions, thank you again for answering!

Edit: Do I have to update past commit messages to adhere to the SE-edu guidelines or is it alright to just do it for future commits? :3

**Comment by damithc** [comment]
> Thank you for the response. I am slightly confused by your second statement. The technique taught in the SE-edu guide seems to enforce capitalisation of the first word in the commit message whereas the convention does not. Wouldn't this mean they do not sit well with each other? In fact, the education guide and convention are both contradicting each other so if the former is always the same for every project, wouldn't it mean the latter is never followed? Sorry for the many questions, thank you again for answering!

The textbook shows you _how to use Git_ (in this case, the _syntax_ of a commit message), which has nothing to do with commit message _conventions_. Git works no matter what case you use in the commit message as long as you follow the syntax.  The textbook is correct because that is a perfectly valid git command.

Conventions are things project team members collectively agree on, in order to follow a consistent style within the project. They are not part of Git and can vary from project to project. In our own projects, we follow a convention of capitalizing the first letter. That's just _our_ convention, not part of Git or a universally agreed rule. It will be incorrect to use the textbook example in one of _our_ projects because that style doesn't comply with our conventions but it might be OK to use it in another project whose conventions require to start with a lower case letter (or doesn't specify which case to use).

> Edit: Do I have to update past commit messages to adhere to the SE-edu guidelines or is it alright to just do it for future commits? :3

No need. Just follow our conventions in future commits.

**Comment by tjtanjin** [comment]
That clears it up a lot, appreciate it. Thank you very much prof @damithc! :)
