### ISSUE TITLE
Updating Checkstyles to version 6.3 in TP?

### ISSUE THREAD

**Issue by rajobasu** [nus-cs2103-AY2021S2/forum#199]
Is it okay if I update checkstyles to v6.3 in the tp?
The version 5.1.2 which was there initially causes it to not run at least on my machine probably due to me running on Java 15? 
However, this seems odd since Java is supposed to be backwards compatible so having a more recent JDK shouldn't break things... which leads me to believe that it can be some other issue? 

![Screenshot 2021-03-02 202701](https://user-images.githubusercontent.com/34958324/109648615-c7f50800-7b95-11eb-822e-ce1cea9639e1.png)

[The above is using checkstyles 5.1.2 and java 15]

**Comment by damithc** [comment]
Official stance: You may use any checkstyle or Java version, as long as the code produced is compliant with the given coding standard and the JAR file works in Java 11. 

Caution: While we allow some flexibility in versions and tools, no help or leniency is available if you mess up while using different tools/versions :-) The best is to use the recommended versions for everything. It will be a disaster if your JAR file doesn't work in Java 11 due to some incompatibility that you failed to notice.
