### ISSUE TITLE
Clarification on milestone names

### ISSUE THREAD

**Issue by tjtanjin** [nus-cs2103-AY2021S2/forum#202]
Hello! I would like to clarify on the names for our milestones. 

This was what was advised in week 7 of the project:
<img width="948" alt="Screenshot 2021-03-03 at 7 38 52 PM" src="https://user-images.githubusercontent.com/43908963/109822878-5939ac80-7c72-11eb-9798-8d8416233e69.png">

This was what was advised in week 8 of the project:
<img width="1022" alt="Screenshot 2021-03-03 at 7 26 33 PM" src="https://user-images.githubusercontent.com/43908963/109822905-60f95100-7c72-11eb-9dfa-6dee073f3813.png">

I am not sure if I have misunderstood any of the above instructions but I am currently confused as to how the milestones should be named for them to be tracked correctly. Specifically, if a weekly iteration approach is taken, should the milestones be named `mid-v1.2` and `v1.2`? Or should they be named `v1.2` and `v1.2b`?

Thank you in advance!

**Comment by damithc** [comment]
That's a valid point @tjtanjin 
We ask you to name the first one v1.2 and the second one v1.2b because the grading script tracks only v1.2. By naming the first one v1.2, you will be able to get credit even if you couldn't finish the second one in time. You can think of the first milestone as 'must have for v1.2' and the second one as 'extra things to do if there is time' (which matches better with the v1.2 and v1.2b names).

**Comment by tjtanjin** [comment]
Alright thank you for the clarification!
