### ISSUE TITLE
Roles and Responsibilites in AboutUs: Is it necessary?

### ISSUE THREAD

**Issue by fairyinabottle4** [nus-cs2103-AY2021S2/forum#210]
My question is because I feel that in my group at least, we are not limited to working on the logic, UI, storage, and whatever other terms that are being used. In other words, we are working on a bit of everything. Therefore it is difficult to categorize our responsibilities. So my question is, can we do away with it? Or if not, could someone suggest a better description? Maybe a list of the specific contributions made to the project?

The same can be said for the roles, our team structure is an egoless democratic one. Could everybody simply be a 'developer' with no team lead further elaboration? 

Hope to hear your responses and suggestions. Thank you.

**Comment by damithc** [comment]
Note that being in charge of a component doesn't mean you are the only one who should be modifying that component. Rather, you are the one who's expected to, know that component best, review changes done to that component in v1.3-v1.4, act as the gate keeper of its quality, help others when they face difficulties while modifying that component etc. Everyone else is expected to modify that component as necessary but because there is one person in charge of it, there is a better chance of that component maintaining its quality through the iterations.

Similar policy applies to other roles. If _everyone is responsible for everything_, then on one is. Besides, it's too much to expect everyone to know everything _well_. That's why you should divide the responsibilities so that each person can afford to go deeper into some things while not needing to do so for other things. That way, if someone in the team needs help with gradle, you know who's job it is to help. Similarly, if something breaks in the build process, you know who should take charge in fixing it.

**Comment by fairyinabottle4** [comment]
@damithc Thank you for your reply. I have a much better idea now. The question then is: How are these roles allocated? It is not as though all of us already have a very deep knowledge of that area with rich experiences. 

This also leads to my original concern, how should they be represented in the AboutUs? I know the obvious answer is "Just list whatever you did" but the reality could possibly be more complex. People might disagree about contribution levels, for example, and insist that they take on a certain role/responsbility as well. Would it be possible in this case, for multiple roles/responsibilities to appear as shared?

**Comment by damithc** [comment]
> How are these roles allocated? It is not as though all of us already have a very deep knowledge of that area with rich experiences.

You have to decide within the team, based on the load, the feature allocation, personal interest, past experience, etc. Yes, it is not totally depending on existing knowledge; some learning is expected. So, it is also a matter of deciding who will need to learn what.

> Would it be possible in this case, for multiple roles/responsibilities to appear as shared?

Not recommended. It's better if people are willing to step up and take charge of things.

![image](https://user-images.githubusercontent.com/1673303/110228272-c97a5380-7f3a-11eb-83cb-6aa9db1a3ba7.png)

In the end, it is still a team decision. We don't actually verify the above or penalize for not following it.
