### ISSUE TITLE
Storage interface in AB3

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#224]
Hi, I have a few questions regarding the storage classes implementation in AB3. 

The `StorageManager` class implements the `Storage` interface, which in turn extends two other interfaces, `AddressBookStorage` and `UserPrefsStorage`. `AddressBookStorage` interface has 5 methods to be implemented and `UserPrefsStorage` has 3 methods to be implemented. Even though `Storage` interface has 5 methods, all 5 of these methods are overriden methods from either of the two interfaces that it extends. Thus, this results in `StorageManger` having to implement all 8 methods.

So, firstly, what is the purpose of the `Storage` interface when the `StorageManager` class can directly implement the two grandparent interfaces?
Secondly, if the answer for the first question is to simply provide a convenient API for the user to see, why did the `Storage` interface only specify 5 of 8 methods? 
(I can understand if 2 of the methods, `readAddressBook` and `saveAddressBook`, are omitted because they are overloaded methods that just provide convenience for user to call, but what about the `getUserPrefsFilePath` method? Shouldn't this `getUserPrefsFilePath` method be specified in the `Storage` interface if `getAddressBookFilePath` is specified too?)

Sorry for the long question but hopefully someone can enlighten me 😅

**Comment by YuFeng0930** [comment]
1. I think it's just for better abstraction purpose. 
2. I think the exclusion of ```getUserPrefsFilePath()``` from ```Storage``` interface is a mistake, as ```getAddressFilePath()``` is included in ```Storage``` interface. But anyways, ```StorageManager``` will still inherit that method from grandparent interface, so it's fine.

Even if we remove ```Storage``` interface completely, the code will still work fine, since ```Storage``` didn't add any new signatures. Hence, I think the existence of that is just to achieve better architecture design and abstraction:))

**Comment by YuFeng0930** [comment]
By the way, I also found AB3 diagram doesn't show the inheritance of ```Storage``` from ```UserPrefsStorage``` and ```AddressBookStorage```, so maybe they intended to let ```StorageManager``` to inherit directly from ```UserPrefsStorage``` and ```AddressBookStorage``` at first.
![image](https://user-images.githubusercontent.com/56251951/110736070-f6de3e80-8265-11eb-8b80-c34fb0eba56e.png)

**Comment by richardcom** [comment]
Hi, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). 
For the first question, I agree with @YuFeng0930 , the implementation is for abstraction purpose. Moreover, I think it is somehow a little bit conventional to do so. Since in many projects, we often have one database(storage) and one database manager(storage manager).

**Comment by damithc** [comment]
> By the way, I also found AB3 diagram doesn't show the inheritance of `Storage` from `UserPrefsStorage` and `AddressBookStorage`

@YuFeng0930 if it is a bug in the diagram, can you report this at https://github.com/se-edu/addressbook-level3/issues ?

**Comment by damithc** [comment]
I had a quick look at the Storage interface. I couldn't think of a good reason to override those 5 methods in there but not the other three. I checked the git blame to see added those five in the first place, and it turns out it was me! 🤦 

This is what I figured happened:
* Initially, I duplicated all the methods that it was inheriting from the other two interfaces, for documentation purposes i.e., the full interface is in one file for easier reference.
* Later, the parent interfaces evolved to have more methods but they were never duplicated in the Storage interface, resulting in this inconsistency. A classic example of duplication leading to unintended inconsistencies.

Why do we have the Storage interface in the first place? Most likely it was added so that we can see the full interface of the Storage component (which is a main component of AB3) in one place. Then, why have those smaller interfaces that Storage inherits from? Most likely to cater for clients that don't need to see the full Storage interface. Relevant: the interface segregation principle https://github.com/se-edu/addressbook-level3/issues

**Comment by w2vgd** [comment]
> I had a quick look at the Storage interface. I couldn't think of a good reason to override those 5 methods in there but not the other three.

> Why do we have the Storage interface in the first place? Most likely it was added so that we can see the full interface of the Storage component (which is a main component of AB3) in one place. Then, why have those smaller interfaces that Storage inherits from? Most likely to cater for clients that don't need to see the full Storage interface. Relevant: the interface segregation principle

Ahhhh I see. Thanks for the clarification prof @damithc. I guess we should update the interface in our own implementation then 😄

**Comment by damithc** [comment]
> By the way, I also found AB3 diagram doesn't show the inheritance of `Storage` from `UserPrefsStorage` and `AddressBookStorage`

Fixed in https://github.com/nus-cs2103-AY2021S2/tp/commit/eccb717df670c4490b09041fb90e730bafaa0e03
