### ISSUE TITLE
RepoSense total LOC and commit LOC do not tally

### ISSUE THREAD

**Issue by banchiang** [nus-cs2103-AY2021S2/forum#225]
Hi prof @damithc so recently made commits that have 200 + lines of contribution but this is not reflected in the total LOC in reposense. My total LOC is currently at 256. But if you would look at the total LOC below it is definitely more than just 250.
![loc](https://user-images.githubusercontent.com/72375578/110739619-7ec74700-826c-11eb-9cdf-1403c663b990.png)

I found out that the issue is in `CalendarWindow.java` that the system does not check all the lines that I have contributed.
![loc cw](https://user-images.githubusercontent.com/72375578/110740099-6c014200-826d-11eb-8876-6769a52b0437.png)

I have over 200 line changed in `CalendarWindow.java` in the commit but only 34 lines is recorded by the system (first part of the file)
![34 loc](https://user-images.githubusercontent.com/72375578/110740234-b2ef3780-826d-11eb-9ccd-48cd5a1c4df5.png)

So only changes up to line 68 are recorded. May I ask is there something wrong here :O?

**Comment by damithc** [comment]
@banchiang we'll look into this in due course. Not to worry about it for the time being. I'll update this thread within a few days.

**Comment by damithc** [comment]
@banchiang it's because there are `@@author` tags in the code that take precedence over git data. That is, some of the code you modified is assigned to a different person using `@@author` tags. In this case the `@@author` tag is used to mark the code as 'reused' and is not counted because of that.
![image](https://user-images.githubusercontent.com/1673303/110750053-e1284380-827c-11eb-9aac-83d3dcbc7833.png)
On a related note, author tags should not contain `{` `}`.

**Comment by banchiang** [comment]
Ah noted thanks prof @damithc I copied those codes so I did not check the author formatting and I have not used the credit formatting as of yet. Will update it and it should be fine thanks!
