### ISSUE TITLE
Access Denied when testing using .bat file

### ISSUE THREAD

**Issue by Eriksen2411** [nus-cs2103-AY2021S2/forum#23]
Remember to give sufficient details e.g.,
* Your development environment (IntelliJ version, Java version, OS, ...)
Intellij 2020.3.1 Community Version, Java 11, Windows 10 64bit
* Relevant code, error message, stack trace
Access is denied.
FC: cannot open ACTUAL.TXT - No such file or folder

Hello Prof and other students. I get the above message when try to run the .bat file in A-TextUiTesting. I think my problem could be the command prompt does not have the write permission to that folder so Actual.txt is not created. I have search Google for some solution but seems like nothing works with me. I don't know if i understand my circumstances correct or not? Please give some help. Thank you. Below is my current repo status after doing level-4 

![image](https://user-images.githubusercontent.com/65208242/105073335-e5788180-5ac1-11eb-92a3-a3b14507461b.png)

**Comment by tjtanjin** [comment]
Hello!

Have you tried running each individual line within the .bat file directly on your command prompt to see if the error messages yield more information?

**Comment by Eriksen2411** [comment]
i have followed your advice and get to know that the problem of "Access denied" is this line:
if not exist ..\bin mkdir ..\bin

**Comment by tjtanjin** [comment]
I am not entirely familiar with windows but have you tried running the command as administrator? If you are able to do so, then there is likely a permission issue and you might want to check the ownership for the affected files/folders. Otherwise, this [article](https://windowsreport.com/administrator-access-denied-windows-10/) contains quite a number of options that you might want to explore.

If all else fails and it's convenient for you, it would be good to list some of the options you tried so that someone more competent can come along to help. Sorry I couldn't do much ;-;

**Comment by Eriksen2411** [comment]
oh thank you for your advice, i ahve tried the command using administrator privilegde and it has clearedd the access denied error. However, i'm left with this error message:
![image](https://user-images.githubusercontent.com/65208242/105132475-f1962a80-5b25-11eb-930e-726fca9b77c9.png)
Actually, when i read about testUiTexting, i realize something that i'm not sure that need to change something or not, and how to change that also. 
![image](https://user-images.githubusercontent.com/65208242/105132750-65383780-5b26-11eb-9330-388104d3bc49.png)
Do you know how can i change that?
For this step, because i don't have Main class so i tried to change that *.java into Duke.java but it results in this:
![image](https://user-images.githubusercontent.com/65208242/105133304-79c8ff80-5b27-11eb-8209-b63322ad768f.png)
Is it because my path is wrong or not? any recommendation for the path change?

**Comment by tjtanjin** [comment]
From what I can see in the screenshot, you are running the command from `C:\WINDOWS\system32`. The paths specified in both the runtest.sh and runtest.bat files however, use relative paths from the `test-ui-test` directory of the project (notice the presence of .. which refers to the parent directory of where you are executing your command). Try running the command inside the `test-ui-test` directory and see if it works :)

**Comment by Eriksen2411** [comment]
oh i managed to get it with your advice. oh and i also think in the same way as your advice also, but i don't know the .. stands for the dir of test-ui-text, i thought it is the path of my cloned repo because in the bath file it got something "..\src\main\java" and src is in the cloned repo folder. why does the relative path acts like that?

**Comment by Eriksen2411** [comment]
oh and btw is this the correct output?
![image](https://user-images.githubusercontent.com/65208242/105135777-8c453800-5b2b-11eb-90d9-d27cc2f6887a.png)

**Comment by candyhy** [comment]
> oh and btw is this the correct output?
> ![image](https://user-images.githubusercontent.com/65208242/105135777-8c453800-5b2b-11eb-90d9-d27cc2f6887a.png)

Hello, based on the picture you attached, I believe that your EXPECTED.txt has some extra spacings somewhere. 
It should show(for windows):
Comparing files ACTUAL.TXT and EXPECTED.TXT
FC: no differences encountered

Hope this helps, thanks!

**Comment by tjtanjin** [comment]
I think it was not explicitly said in the instructions to run the scripts within the `test-ui-test` directory. That said, `..` does not actually refer to `test-ui-test`, rather, it refers to the parent directory of wherever you were running your command from. When you originally ran the command from `C:\WINDOWS\system32`, `..` would have brought you up one directory to WINDOWS. When ran from the `test-ui-test` folder, `..\src\main\java\*.java` first moves up one directory to iP (project folder), then it looks for `src` which it can find in the project folder, then `main`, `java` and finally all the java files inside the java folder.

When you see relative paths specified, it is almost certain you need to run the script from a specific directory (otherwise it is likely you will not be able to find some of the files). At this point you might think why not just use absolute paths, but keeping paths relative does make the program more portable (it's plug and play most of the time). Both have their pros and cons, hope this clarifies :D

**Comment by damithc** [comment]
Thanks @tjtanjin for the continued help with this issue 💯 

@Eriksen2411 the following may be useful to you:
![image](https://user-images.githubusercontent.com/1673303/105136901-67ea5b00-5b2d-11eb-8dce-f0c489343b72.png)

**Comment by Eriksen2411** [comment]
@candyhy thank you for pointing that out for me.
@tjtanjin thank you so much for your help for my issues
@damithc Thanks prof, that was really helpful as i don't know .. refers to the parent dir

**Comment by Eriksen2411** [comment]
Solved and closed
