### ISSUE TITLE
Discussion: Law of Demeter - does it really worth the effort to refactor?

### ISSUE THREAD

**Issue by tlylt** [nus-cs2103-AY2021S2/forum#240]
LOD says this is bad:
```
Class A {
   void doStuff(B b) {
       b.getC().doCStuff();
  }
}
Class B {
   C c;
   C getC() {
      return c;
  }
}
```
I can understand why that is the case, but on second thoughts I wonder when the above code is refactored in the following way, is it really better?
```
Class A {
   void doStuff(B b) {
       b.doCStuff();
  }
}
Class B {
   C c;
   void doCStuff() {
      getC().doCStuff();
  }
}
```
Pros
- If calling `doCStuff` method is common, then `b.doCStuff()` is more convenient than having to use `b.getC().doCStuff()` all the time.

Cons
- Sometimes it may not feel right to have such a `doCStuff` method within class B?

**Comment by damithc** [comment]
It's a good point to discuss.
Also, don't forget this alternative i.e., make the C a direct 'friend' of A:
```java
Class A {
   void doStuff(C c) {
       c.doCStuff();
  }
}
```

**Comment by JulietTeoh** [comment]
I think that 
`Class A {
   void doStuff(B b) {
       b.doCStuff();
  }
}
Class B {
   C c;
   void doCStuff() {
      getC().doCStuff();
  }
}` 
really is worth the effort in refactoring, because it can really help cut down on possible bugs and mistakes that are likely to arise when you add more code to class A's doStuff() method. Also, having getters that gets class C can make any changes to class C or B especially tedious in the long run, which strengthens the case for refactoring. 

I think that it might not always be applicable to do
`Class A {
   void doStuff(C c) {
       c.doCStuff();
  }
}`
For instance, A can be personListManager and B can be a person and C can be the person's name. It does not really make sense for A to directly call c.doCStuff, as it may only be managing B (that contains C), and can also become an unnecessary association that can make the code overly complicated in the long run.

**Comment by damithc** [comment]
> I think that
> `Class A { void doStuff(B b) { b.doCStuff(); } } Class B { C c; void doCStuff() { getC().doCStuff(); } }`
> really is worth the effort in refactoring, because it can really help cut down on possible bugs and mistakes that are likely to arise when you add more code to class A's doStuff() method. Also, having getters that gets class C can make any changes to class C or B especially tedious in the long run, which strengthens the case for refactoring.

@JulietTeoh heads up: the code blocks in your post doesn't seem to be formatted correctly.
