### ISSUE TITLE
Clarification on use of screenshots in UG

### ISSUE THREAD

**Issue by tjtanjin** [nus-cs2103-AY2021S2/forum#261]
Hello,

For the user guide, I understand there were mentions of including only relevant parts of the application in a screenshot (so that they need not be frequently changed with updates). However, on the other hand, the tradeoff is that it is up to the user to identify which part of the application the screenshot is referring to.

That said, if the team feels that the UI is unlikely to receive frequent updates once it has been finalised, would it not be neater to display the entire application to the user (perhaps with annotations) so that at one glance they immediately know which part of the application to look out for? I imagine this saves time for the user and also eliminates room for confusion.

This brings me on to the following point:

<img width="811" alt="Screenshot 2021-03-26 at 4 22 49 PM" src="https://user-images.githubusercontent.com/43908963/112603964-a1eb1c80-8e50-11eb-9377-f149782a96ee.png">

If a screenshot of the entire application is used, it will undoubtedly appear repetitive in the sense that there will be the same layout present in every screenshot. However, I am not sure if this would necessarily impair a user's experience, given that unfamiliar users might appreciate having the full picture. After all, the issue seems more to be the ease of maintenance. May I thus clarify if using full screenshots showing the different states/commands of an application will automatically count as a bug?

Thank you in advance!

**Comment by damithc** [comment]
> However, on the other hand, the tradeoff is that it is up to the user to identify which part of the application the screenshot is referring to.

That's a fair point. For cases where you anticipate the user will find it hard to identify which part it is, you can go with a screenshot that shows more context. It should be fine if the evaluators agrees with you that the bigger screenshot is warranted for those cases.

**Comment by tjtanjin** [comment]
In that case, would citing personal preferences for a user guide that shows the full screenshot of the application even if the individual components are not hard to identify be legitimate?

I am mainly thinking that if the primary advantage of using partial screenshots is to ease maintenance (do not have to frequently update screenshots), then the decision to use full screenshots should rest on the developer team (i.e. if the team feels UI updates will not be frequent and wishes to include the full screenshot, it should not be flagged as a bug). 

The above is of course assuming there is no 'harm' done to the users reading the guide which I am doubtful will happen because a full UI screenshot is likely to be even more straightforward.

**Comment by damithc** [comment]
> In that case, would citing personal preferences for a user guide that shows the full screenshot of the application even if the individual components are not hard to identify be legitimate?

They will be evaluating it from the perspective of a future developer. So, their own judgement carry weight. 
Also, this is not strictly about the convenience of maintenance. In some cases, just seeing the relevant parts only is easier on the reader as well. 
In the end, if the use of screenshots is within the ballpark of a reasonable tradeoff, it will not count as a bug. Only going to extremes on one or the other so that it is clearly 'excessive' will be counted as a bug. You can go with your preferred approach and see how others respond during the PE dry run. Also, after having seen other UGs during the PE-D, you can revisit the decision and refine if necessary. This kind of things can benefit from iterative refinement as sometimes you have to actually 'see' the result to decide if it is good or bad.

**Comment by tjtanjin** [comment]
Ok thank you for the clarification!
