### ISSUE TITLE
How do we handle bug reports that suggest a change to a feature

### ISSUE THREAD

**Issue by VRSoorya** [nus-cs2103-AY2021S2/forum#289]
Some of the acceptance test bug reports from the PE-Dry run seem to suggest functionality changes or enhancements to a feature. Is that allowed in v1.4 as a "bug fix" or do we ignore these bug reports? 

For quick reference from the course website:
![image](https://user-images.githubusercontent.com/50356777/113499556-80bdb680-9549-11eb-883a-5bf229d31880.png)

**Comment by yhtMinceraft1010X** [comment]
Personally, I think it should be okay if it is a minor change that can be implemented very easily in response to a bug report.

This is up for debate though. What does everyone else think?

**Comment by damithc** [comment]
The goal of freezing features in the pre-release iteration is to subject the features to at least ~~two rounds of testing~~ one round of non-dev testing before releasing to the users. In a real project minor or critical changes might be allowed even near a deadline -- but here, we don't want to allow _any_ because it can start us on a slippery slope and many 'is this allowed?' queries. Therefore, functionality changes are not allowed (i.e., there should not be any feature that was not already tested in the PE-D). 

You can ignore those issues (i.e., to be considered in a future version beyond v1.4) or close them (to reduce clutter in the issue tracker).

**Comment by VRSoorya** [comment]
Alright, thanks prof!
