### ISSUE TITLE
Clarification: referencing user guide in error messages

### ISSUE THREAD

**Issue by tjtanjin** [nus-cs2103-AY2021S2/forum#299]
Hello!

With reference to [this issue](https://github.com/nus-cs2103-AY2021S2/forum/issues/296) that was asked, I would like to check if it is alright for an error message to not actually contain information on the correct format of the command (which can be really ugly/cluttered if it is long with multiple compulsory, optional and repeated parameters). Instead, only information on the error will be provided and users are then told to check out the user guide for the command format. 

My concern is that a possible bug testers may raise is that "the application does not provide information for the command format", arguing that referring to the user guide is a hassle. However, a counter argument could also be made that the purpose of a user guide is to accurately and detailedly note those information and as an extension, having only one "true source" of information (the UG) is easier to maintain and less prone to mistakes.

Could anyone advice on this?

Thank you!

**Comment by kouyk** [comment]
I do share the same thoughts as you, as maintaining several copies of the same information is not only time-consuming, but also very error-prone. However, pointing the user to the user guide every single time means that we are now reliant on a remote server, which is a violation of one of the TP constraints.

**Comment by tlylt** [comment]
The point on one true source of information is interesting. I think the one true source of information ... is the **CODE** 🤓 

Jokes aside, I feel that the issue lies in what information is treated as important enough to display to the user in a convenient manner. If it is important, perhaps there is no harm having it in both places. 

On top of that, this makes me wonder about the features of this very forum that we are using. Perhaps the better alternative is to have a way for users to indicate what level of help they need so that an adequate level of error message can be provided. Much like the forum, the participants get to decide whether the discussions are important enough to enable the notification by email feature provided by Github, which they can indicate via 'watching' the repo. Of course, this may be far-fetched in the TP context. I am interested to hear what others have to say.

**Comment by tjtanjin** [comment]
> However, pointing the user to the user guide every single time means that we are now reliant on a remote server, which is a violation of one of the TP constraints.

I assume this might actually be alright because `help` command itself contains a link to the project web page (which includes the guides). Please correct me if I misunderstood this though ;-;

> Jokes aside, I feel that the issue lies in what information is treated as important enough to display to the user in a convenient manner. If it is important, perhaps there is no harm having it in both places.

I think this highlights the main issue, that what one feels is important information may not be the same for the other (in this case, let's just say there will be people who prefer a clean interface with all the information in the user guide and there will be those who want every information also in the app). 

I am under the impression that many of the successful products got to where they are today through diligent research and perhaps many prototypes to establish the preferences/needs of the user. Sadly, owing to the time constraints for tP, such efforts are near impossible and so it starts to feel more like a square off between "your opinion vs mine". That said, I then feel compelled to add as much information as possible (so that I cannot get called out for a lack of information) but this may also come around to bite me, because now too much information is hard to read. Wouldn't have imagined this to be a real struggle... ;-;

**Comment by tlylt** [comment]
> > However, pointing the user to the user guide every single time means that we are now reliant on a remote server, which is a violation of one of the TP constraints.
> 
> I assume this might actually be alright because `help` command itself contains a link to the project web page (which includes the guides). Please correct me if I misunderstood this though ;-;
> 
> > Jokes aside, I feel that the issue lies in what information is treated as important enough to display to the user in a convenient manner. If it is important, perhaps there is no harm having it in both places.
> 
> I think this highlights the main issue, that what one feels is important information may not be the same for the other (in this case, let's just say there will be people who prefer a clean interface with all the information in the user guide and there will be those who want every information also in the app).
> 
> I am under the impression that many of the successful products got to where they are today through diligent research and perhaps many prototypes to establish the preferences/needs of the user. Sadly, owing to the time constraints for tP, such efforts are near impossible and so it starts to feel more like a square off between "your opinion vs mine". That said, I then feel compelled to add as much information as possible (so that I cannot get called out for a lack of information) but this may also come around to bite me, because now too much information is hard to read. Wouldn't have imagined this to be a real struggle... ;-;

Personally, I have much faith in the teaching team to be the judge should such "your opinion vs mine" situation arises. 

We can never stop testers from raising silly bug reports. If we think as developers of the product, we have our (reasonable & logical) ground of implementing certain features with our target users in mind, then that's pretty much settled in the TP context (At least that's what I believe). The fact that different people may have different opinions about what clean interface means should not be an issue that will cloud the judgments of the teaching team. I believe they are much more experienced in dealing with such raucous. 
I believe Prof and TAs will be fair judges to that end, wouldn't they?

**Comment by tjtanjin** [comment]
I don't doubt the professionalism of the team, but there exist a very real possibility that despite best efforts deciding on the best course of action to take, one may be penalised because of a mismatch of preferences (people will have their own inherent bias, regardless how small it may be). Perhaps it would be more reassuring if more details can be shared on how such subjectivity is addressed when the bugs are being reviewed by the team. I can understand why a "fix standard" is not given because then everyone will just follow it strictly but leaving this so open-ended is also quite unnerving. Or maybe... too much overthinking ._.

**Comment by ong6** [comment]
In Damith we trust!

Even Grammarly says to have faith in him 
![image](https://user-images.githubusercontent.com/19247856/114034641-37b07f80-9833-11eb-8b18-8673c82d60bb.png)

**Comment by tlylt** [comment]
I would say that the possibility of a decision not in the developers' favor is indeed a real one. 
Two cases:
- Teaching team is with the developers, nothing much to say.
- Teaching team not with the developers:
That means the teaching team has reasonable ground to believe that our feature lacked the consideration for users, which was rightly pointed out by the tester. When that is the case, which happens all the time for open-ended questions, is how we as developers view the opinion of others. We can certainly accept it and acknowledge the shortfall on our end. Or we can raise our case and state our stand. If that appeal is rejected, we can still keep our opinions to ourselves and accept that the official stance of CS2103T is as such. This does not mean that our opinion is wrong, in some cases, it simply means our opinion is different. 

Perhaps I am putting too little concern with marks...

**Comment by tlylt** [comment]
On second thoughts, will the tester be penalized for raising invalid bug reports? I would imagine if this is the case, it will greatly deter silly bugs from being reported.

**Comment by tjtanjin** [comment]
> On second thoughts, will the tester be penalized for raising invalid bug reports? I would imagine if this is the case, it will greatly deter silly bugs from being reported.

To this end the points in this issue would apply to the tester as well. Now as a tester I am actually scared to submit a bug report, not because I am trying to game the system with silly reports but because of the very same subjectivity mentioned above ;-;

**Comment by tlylt** [comment]
> > On second thoughts, will the tester be penalized for raising invalid bug reports? I would imagine if this is the case, it will greatly deter silly bugs from being reported.
> 
> To this end the points in this issue would apply to the tester as well. Now as a tester I am actually scared to submit a bug report, not because I am trying to game the system with silly reports but because of the very same subjectivity mentioned above ;-;

I think that means if the teaching team thinks that both sides have a valid point (for ambiguous issues), then the bug report should be voided with no penalties to both parties. Will that solve the problem?

**Comment by damithc** [comment]
This one involves a trade-off between user convenience and developer convenience. We have to strike a balance. Where to draw the line? As you know, there is no magic formula to apply. As some of you have mentioned, it can also vary based on personal preferences. Beware of prioritizing developer convenience over user's though. If users are unhappy, it doesn't matter how easy it is to maintain the code.

Hence, likely some duplication is inevitable. There may be clever ways to define the content in one place but display in multiple places, but probably not within reach of tP.

Will giving a lot of details annoy the user? It can, but we can mitigate the problem by formatting the error information better. e.g., put the critical info at the top and details below so that the user can stop reading if not interested in details.

From the user POV, I think having the relevant info displayed in the error message is better than having to go look at the UG, especially if there is no easy way to go to the relevant UG section directly.

Outcome-wise, when there is an error in the command, perhaps it is OK if the user needs to go look at the UG on rare occasions, which means the error message is sufficient to educate the user in most cases. For example, `The date format is incorrect. Suggested format: dd/mm/yyyy See user guide for other supported formats`

As for PE, it should be fine as long as you don't try to game the system purposely. Some borderline cases can go either way (we'll try to be as impartial and objective as we can when it's our decision). 

There is no penalty for reporting incorrect bugs. There are some bonus marks if a tester shows a high accuracy rate e.g., >70% -- intended to reduce testers overstating the bug's severity/type to 'try their luck' (e.g., some testers tend to report everything as `severity.High`).

**Comment by tjtanjin** [comment]
Thank you all for the discussion/clarifications! :)
