### ISSUE TITLE
No commit message on auto-merge after resolving merge conflicts

### ISSUE THREAD

**Issue by tjtanjin** [nus-cs2103-AY2021S2/forum#30]
Hello,

I was working on increment Level-7 and Level-8 in their respective branches. After finishing both of them, I forced git to create a merge commit using the `--no-ff` flag as shown below:
```
git merge --no-ff branch-Level-7
```
This worked for merging Level-7 with my master but merging Level-8 raised up merge conflicts with the following message:
```
java_projects/ip$ git merge --no-ff branch-Level-8
Auto-merging src/main/java/Command.java
CONFLICT (content): Merge conflict in src/main/java/Command.java
Automatic merge failed; fix conflicts and then commit the result.
```
I thus went ahead to resolve the conflicts, add and commit the files within the master branch (kindly advice if this is the correct branch to resolve conflicts on). After committing the modified files and running the merge command again, I was greeted instead with an `Already up to date` message. Pushing the commits however, did not create a commit message despite me specifying the `--no-ff` flag earlier. Is this expected behaviour?

Edit: Added screenshot of the commit history on my master branch in case the explanation above was not clear enough :3

<img width="1232" alt="Screenshot 2021-01-22 at 10 04 09 PM" src="https://user-images.githubusercontent.com/43908963/105500683-2ceb5180-5cfe-11eb-9731-8fbaf49e415a.png">

Thank you!

**Comment by galvinleow** [comment]
Before the other students begin helping you out, could you provide a screenshot of the tree structure for your repository? It would be a better visualisation for others on the status of your tree.

**Comment by w2vgd** [comment]
Hi @tjtanjin, I believe what you have now is already correct. The latest commit shown in the screenshot above (with hash 83e2ae5) is the result of the merge between the `master` branch (which was already merged with the `branch-Level-7` branch previously) and the branch `branch-Level-8`. 

> ```
> java_projects/ip$ git merge --no-ff branch-Level-8
> Auto-merging src/main/java/Command.java
> CONFLICT (content): Merge conflict in src/main/java/Command.java
> Automatic merge failed; fix conflicts and then commit the result.
> ```

When you run this command which attempts to merge `branch-Level-8` with branch `master`, there is a merge conflict and you went on to modify the files and probably ran `git add` (which marks the file as resolved), followed by `git commit` (which actually finalizes the merge conflict, i.e. commits it). 


> I thus went ahead to resolve the conflicts, add and commit the files within the master branch (kindly advice if this is the correct branch to resolve conflicts on). After committing the modified files and running the merge command again, I was greeted instead with an `Already up to date` message. Pushing the commits however, did not create a commit message despite me specifying the `--no-ff` flag earlier. Is this expected behaviour?

Therefore, when you run the `git merge` command again, the system prompts you that it is already up to date because the `master` branch is already merged with the `branch-Level-8` branch. I believe after this you do a `git push` command to push the changes from your local repo to your remote repo and hence you have 4 commits as shown.
The 4 commits are correct from the steps you took, with their messages originating from:
1. The commit message from committing in `branch-Level-7`
2. The commit message from  committing in `branch-Level-8`
3. The commit message from merging branch `branch-Level-7` with `master`
4. The commit message from merging branch `branch-Level-8` with `master` (you probably wrote "Fix: fix merge conflicts" when you finalize the merge command with `git commit` as explained above)

**Comment by tjtanjin** [comment]
@galvinleow @w2vgd Thank you for the help! Just got a bit uncomfortable and worried when I didn't see a merge commit message despite forcing it in the command :P
