### ISSUE TITLE
Clarifications on a few bug scenarios

### ISSUE THREAD

**Issue by tjtanjin** [nus-cs2103-AY2021S2/forum#326]
Hello! I would like to make a few clarifications on whether the following could be considered legitimate bugs:

1) Are cluttered/hard to read UI considered a bug or are these considered aesthetics and out of scope?

2) Are mismatched headings considered a bug (for example the section heading in the content table has 1-2 words missing compared to the actual section heading)?

3) Are inconsistent full stops in bullet points also considered a bug?

Would appreciate some advice since most of the above would not really hinder the usage of the application/guide.

Thank you!

**Comment by damithc** [comment]
> * Are cluttered/hard to read UI considered a bug or are these considered aesthetics and out of scope?

Given the short time you had to implement the feature, there is room for you to argue that there was not enough time do a better UI and hence this is `NotInScope`.  But this also depends on how much of a hindrance the problem is and how much additional effort it would have taken to do a better design.

> * Are mismatched headings considered a bug (for example the section heading in the content table has 1-2 words missing compared to the actual section heading)?

Yes, but `severity.VeryLow` (i.e., it is something that needs fixing, hardly any penalty for the dev, but the tester will get credit for spotting it)

> * Are inconsistent full stops in bullet points also considered a bug?

Same as above.

**Comment by tjtanjin** [comment]
Ok thank you very much for the clarifications!
