### ISSUE TITLE
Request for usage approval for Jackson

### ISSUE THREAD

**Issue by stein414** [nus-cs2103-AY2021S2/forum#41]
## Library

[Jackson](https://github.com/FasterXML/jackson)

## Purpose

For serialising and de-serialising POJO. 

## License

Apache License 2.0
https://github.com/FasterXML/jackson-core/blob/master/LICENSE

**Comment by damithc** [comment]
Approved.

**Comment by DrWala** [comment]
Prof @damithc, In line with this, can we use Maven to manage the dependencies?

**Comment by damithc** [comment]
> Prof @damithc, In line with this, can we use Maven to manage the dependencies?

You mean instead of Gradle?

**Comment by damithc** [comment]
Also, what's the connection between Maven and this library? 🤔

**Comment by DrWala** [comment]
Perhaps I am misunderstanding something, allow me to clarify my thought process:
As Jackson is a 3rd party dependency, there are 2 ways to manage it.

- we can add it to the classpath manually
- we can use a package manager to manage our dependencies

From my understanding, Gradle is meant for build automation, but Maven is meant to do dependency management (Perhaps I am wrong about this)

With that reasoning in mind, I asked if we should use Maven to manage Jackson, so that version updates etc can be quickly and easily taken care of by updating the pom.xml file. However, if Gradle can do this as well, then it would make more sense to use Gradle as the project is already intending to use it down the road.

Do let me know if this makes sense 😅

**Comment by damithc** [comment]
@DrWala Got it. Yes, now I understand your request.

Gradle does both: build automation and dependency management. So, no need to use Maven.

Others reading this post: Gradle will be covered in a future week, in case you are puzzled what that is.

**Comment by DrWala** [comment]
Understood, will figure out how to manage Jackson through Gradle.

Thank you Prof!
