### ISSUE TITLE
How should I test methods that return void?

### ISSUE THREAD

**Issue by fairyinabottle4** [nus-cs2103-AY2021S2/forum#50]
Hi everyone, I was just wondering how certain methods that return void can be tested(such as `public static void main`) since these methods do not return anything, hence there would be nothing to compare with. Please correct me if I am wrong, or offer some suggestions. Thank you

**Comment by tjtanjin** [comment]
For a void method I think it depends on what the method itself achieves. I had a similar situation where my void methods were merely printing outputs and this [guide](https://www.baeldung.com/java-testing-system-out-println) here proved very helpful. In another scenario, it is possible that a void method alters a particular attribute of an object and in that case, I believe checking if the attribute was altered successfully would suffice. For these cases, the `@BeforeEach` and `@AfterEach` annotations would come in useful.

**Comment by rajobasu** [comment]
By the way, is the following true?
- check only methods which are returning something — ie very modular. 
- if method is not functional, then it means it is a series of steps which should be clear from the method name itself so why test? If there is additional computation, maybe just shift it to other methods and repeat step 1.

**Comment by richardcom** [comment]
I think that a method either does the job of returning sth or results in side effects. Thus, in this case I guess you meant for methods with side effects. I think that you can call the method check if the side effects have taken place.

For example, you can create a new X object in your test and call the method on X. See later if any attributes of X is changed because of the side effect. If it is changed correctly, then the method is tested to be valid.

**Comment by fairyinabottle4** [comment]
Thank you for the response, this was an enlightening discussion :)
