### ISSUE TITLE
Why use "finally" block?

### ISSUE THREAD

**Issue by nowknowing** [nus-cs2103-AY2021S2/forum#55]
This was covered a while ago in Week 2 readings, but it has only become a question now.
Might there be a case where we must have a "finally" block,
in other words, a case where we cannot just go out of the try-catch blocks?

![image](https://user-images.githubusercontent.com/49021362/105956811-52d47580-60b3-11eb-97e5-78b031d3fbf4.png)
In other words, how is cleaning up and finishing method different?

**Comment by georgepwhuang** [comment]
From my understanding, the `finally` block is used for resource releasing. As in although Java has a garbage collector, there are still some classes/objects you'll have to manually close, such as files. So if you opened a file in a `try` block, you'll have close it in the `finally` block, because the `finally` block would execute regardless.

I think this link would help:
[https://docs.oracle.com/javase/tutorial/essential/exceptions/finally.html](https://docs.oracle.com/javase/tutorial/essential/exceptions/finally.html)

**Comment by rajobasu** [comment]
You might also want to look at try-with-resources, which basically closes ```AutoClosable``` objects automatically. 
Second, @georgepwhuang mentioned about garbage collectors, related to that is the ```finalize()``` method as well. 
It is called just before the object is to be garbage collected. However there is a caveat here. Look at the following code: 

```
Class A {
    static A ref = null;
    static boolean x = false;  
    public void finalize() {
        if(x) {
            
              // close some stuff ( —— line (1) )
            return;
        }
        A.ref = this;
        A.x = true;
    }
    public static void main(String… args) {
        A a = new A();
        a = null;
        // force garbage collector, lets say (even though you can’t do it, but just for argument) to garbage collect the object.
        a = A.ref;
        A.ref = null;
        // again force gc.
    }
}
```

You would assume that the line(1) would be called atleast once right?
Turns out no!!!

The first time the object is garbage collected, we forcefully keep a reference. So it is not garbage collected.
The second time, that garbage collector **doesn’t call finalize()** at all! 
It’s only called the first time the object is about to be garbage collected. ONLY THEN.
As a corollary, I also showed how after calling finalize, the garbage collection might get botched altogether!

**Comment by nowknowing** [comment]
> 
> 
> From my understanding, the `finally` block is used for resource releasing. As in although Java has a garbage collector, there are still some classes/objects you'll have to manually close, such as files. So if you opened a file in a `try` block, you'll have close it in the `finally` block, because the `finally` block would execute regardless.

Thank you for your response, I am learning new things, like about garbage collecting I had no idea was related.

But if Im not failing to get something, I still think my question remains: 
is 'finally' block any different from putting its codes outside the try-catch block?
i.e. why can't we just close the file outside the entire 'try-catch' block
And to which, I think I have some idea now. 

> But finally is useful for more than just exception handling — it allows the programmer to avoid having cleanup code accidentally bypassed by a return, continue, or break.

^ I got this from the link @georgepwhuang shared

https://stackoverflow.com/questions/18251156/uses-of-the-finally-statement/18251196
