### ISSUE TITLE
Committing of .class file into GitHub

### ISSUE THREAD

**Issue by ssoonwee** [nus-cs2103-AY2021S2/forum#58]
Hi guys,
I am not sure if I am doing the right way of running javac *.java and commiting all the .class file. I do not commit everytime I compile, only the time when I finalized with doing a task. From what I see now, it looks quite okay, but if say, we are going to implement more classes in the future, there would be too many stuffs within a certain directory. Is this considered as a 'right' way or a bad practice? What are your thoughts on this? 
![image](https://user-images.githubusercontent.com/38690268/106101527-fb98d880-6178-11eb-842a-2e9efcdbbf53.png)

**Comment by SoonKeatNeo** [comment]
Personally, I don't think it's a good idea to commit compiled files unless there is a good reason for doing so. By definition, since git is primarily a version control tool, it makes sense to want to version control the source files instead of the compiled product.

Additionally, I believe you may run into issues with rebasing later on (if you have the need to do it) with the inclusion of compiled files.

**Comment by damithc** [comment]
> Personally, I don't think it's a good idea to commit compiled files unless there is a good reason for doing so. By definition, since git is primarily a version control tool, it makes sense to want to version control the source files instead of the compiled product.

Correct. Best not to add binary or generated files to a repo unless there is a very strong reason to do so.

**Comment by noelmathewisaac** [comment]
To add on, when you run the Duke.java (or your Main java file) in Intellij, the .class files are generated and stored in the bin directory. This directory is not committed because it's excluded in the .gitignore file. So you could consider adding `/src/main/java/*.class` to your .gitignore file to exclude the .class files.

**Comment by ssoonwee** [comment]
Okay thanks all for your feedback. I will now close this.
