### ISSUE TITLE
Regarding empty catch clause

### ISSUE THREAD

**Issue by w2vgd** [nus-cs2103-AY2021S2/forum#59]
Hi, may I ask if the java convention disallow empty catch clauses? 

In my use case below, I am allowing users to pass in multiple date/time formats, for e.g. 23/1/2021 1800 and just 23/1/2021. Thus, I created an enum `InputDateFormat` that specifies different date/time formats (also, is the use of an enum here appropriate?). Then when I try to parse the user input date string, I use a for loop to loop through all the date/time formats (the enums values) and attempt to parse them into a `LocalDateTime` object. If the first attempt fails, I catch the exception and continue the for loop to attempt to parse again.

Is this a valid way to use empty catch clauses? Or should I re-implement this design in another way? (Or does anyone have any suggestions on how we can handle multiple date/time formats?)

![image](https://user-images.githubusercontent.com/65358857/106134747-f2703180-61a1-11eb-95fd-5ad0dd514350.png)

**Comment by damithc** [comment]
Not an answer, but a comment to guide future answers:

> Hi, may I ask if the java convention disallow empty catch clauses?

If you are referring to our coding standard, this is a matter of checking the coding standard to see if it prohibits empty catch blocks.

However, even if the answer to the above question is 'allowed', the second part of the question is still worthy of discussion. Just because something is allowed by the coding standard doesn't mean it is OK to use it.

**Comment by rajobasu** [comment]
I believe that in this specific scenario, there are two things we can essentially do: 
 - As OP mentioned, we can leave it as a blank catch since it doesn’t make sense to do anything with the exception. Indeed, upon some digging this might also be the Oracle recommended way? Look at [this](https://docs.oracle.com/javase/tutorial/datetime/iso/format.html) article, seems like there is no testParse() function available anyway, the main way to deal with this error is throwing an exception. 
 - Second, which I think is better albeit tedious, is to fix the input to a particular format and then regex it yourself before making a LocalDateTime from it, since throwing Exceptions is a very costly thing to do in a program just like that. 

In general, Exceptions are supposed to deal with **exceptional** situations, which is not so in this case obviously. Hence, they in general should be dealt with by a non-empty code block.

**Comment by tjtanjin** [comment]
I used an empty catch myself but I really love the suggestion from @rajobasu to use regex. In my case the use of regex would make my code for parsing simpler and neater as well so I will probably refactor my code around this, thanks :D

**Comment by w2vgd** [comment]
I have noted that a `LocalDateTime` object has to have both a date and time field, so when the user pass in only a date format, e.g. `LocalDateTime.parse("23/1/2021", DateTimeFormatter.ofPattern("d/M/y"))` actually returns an error. In this case, my original for loop will fail too. 

Therefore, I have decided to parse the date and time strings separately and use both a `LocalDate` instance attribute and a `LocalTime`  instance attribute in my `DeadlineTask` class to describe the full date and time. Am thinking if just using a simple split method over using regex to parse the input date and time will be better in this case.

Thanks @rajobasu for the suggestion!
