### ISSUE TITLE
Discrepancy between checkstyle file and java coding standard

### ISSUE THREAD

**Issue by tjtanjin** [nus-cs2103-AY2021S2/forum#66]
Hello!

I would like to highlight the following discrepancies between the checkstyle file and java coding standard:

1) Screaming snake case not enforced for private attributes in checkstyle file.

2) Javadocs header comments not enforced for getters, setters and constructors.

I am under the impression the java coding standard takes precedence over the checkstyle file so it might be best to manually check for the above until the discrepancies are sorted out :D

**Comment by zhoube** [comment]
I think that checkstyle also insists on not having any whitespace lines while the Coding Standard says that in some cases separating the lines by logic is fine

**Comment by tjtanjin** [comment]
@zoeykobe Do you know specifically when this happens?

**Comment by damithc** [comment]
> I would like to highlight the following discrepancies between the checkstyle file and java coding standard:
> 
> 1. Screaming snake case not enforced for private attributes in checkstyle file.
> 2. Javadocs header comments not enforced for getters, setters and constructors.

Thanks for bringing this up @tjtanjin 

1. I think we should use the SCREMING_SNAKE case for all constants, both private and public. You can update the checkstyle file accordingly (a good exercise to learn a bit about the checkstyle config file) or check it manually.
2. I'll update the coding standard to exempt these three from the javadoc requirement. Otherwise you could end up writing lot of redundant javadoc comments.

**Comment by damithc** [comment]
> 2\. I'll update the coding standard to exempt these three from the javadoc requirement. Otherwise you could end up writing lot of redundant javadoc comments.

Done.

**Comment by tjtanjin** [comment]
Thank you for the clarifications :D
